include: package:flutter_lints/flutter.yaml

exclude:
  - "strings.dart"

analyzer:
  strong-mode:
    implicit-dynamic: true
    implicit-casts: true
  errors:
    unused_import: warning
    unused_local_variable: warning
    dead_code: warning
  enable-experiment:
    - extension-methods

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false
    non_constant_identifier_names: false
